# Copyright Cyral, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.11.2
description: A Helm chart for the Cyral Repo Crawler
home: https://cyral.com
keywords:
- cyral
- crawler
- database security
name: crawler
type: application
maintainers:
- name: Cyral, Inc.
  url: https://github.com/cyralinc/cyral-helm-crawler
sources:
- https://github.com/cyralinc/cyral-helm-crawler
version: 0.1.0
