controlPlane: "stable.dev.cyral.com"

credentials:
  existingSecret: "my_existing_secret"

cronjob:
  env:
      - name: Extra_var
        value: xyz
  repoName: "repo_name"
  repoCredentials:
    existingSecret: "my_existing_secret"
  schedule: "0 0 * * 6"
  serviceAccount:
    name: sa-user
    create: false
