{{- /*
Copyright Cyral, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if ( include "cyral.createCpCredentialsSecret" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cyral.cpCredentials.secretName" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.credentials.labels .Values.commonLabels ) "context" . )  }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.credentials.annotations }}
  {{- $annotations :=  include "common.tplvalues.merge" ( dict "values" ( list .Values.credentials.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  clientId: {{ .Values.credentials.clientId | b64enc | quote }}
  clientSecret: {{ .Values.credentials.clientSecret | b64enc | quote }}
{{- end }}