{{- /*
Copyright Cyral, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if ( include "cyral.createRepoCredentialsSecret" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cyral.repoCredentials.secretName" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.cronjob.repoCredentials.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.cronjob.repoCredentials.annotations }}
  {{- $annotations :=  include "common.tplvalues.merge" ( dict "values" ( list .Values.cronjob.repoCredentials.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ .Values.cronjob.repoCredentials.username | b64enc | quote }}
  password: {{ .Values.cronjob.repoCredentials.password | b64enc | quote }}
{{- end }}