{{- /*
Copyright Cyral, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.cronjob.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cyral.serviceAccountName" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.cronjob.serviceAccount.labels .Values.commonLabels ) "context" . ) }}
  labels: {{ include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4}}
  {{- if or .Values.cronjob.serviceAccount.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.cronjob.serviceAccount.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- end }}
