name: Lint Charts PR

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Run chart-testing (list-changed)
        run: |
          for file in ./examples/*.yaml; do
            echo "Linting file: $file"
            helm lint -f "$file"
          done
